---
- name: Lab04 undo
  hosts: ansible2.example.com
  become: true
  gather_facts: false
  tasks:
    - name: Disable Apache service
      ansible.builtin.service:
        name: httpd.service
        state: stopped
        enabled: false
    - name: Uninstall Apache httpd
      ansible.builtin.dnf:
        name: httpd
        state: absent
    - name: Install firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: present
    - name: Enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
#    - name: Open Firewall (enable http & https) # cmd: 'firewall-cmd --permanent --zone=public --add-service=http --add-service=https'
#      ansible.builtin.command:
#        cmd: 'firewall-cmd --permanent --zone=public --add-service=http --add-service=https'

    - name: Disable http & https # cmd: 'firewall-cmd --permanent --zone=public --add-service=http --add-service=https'
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: disabled
        immediate: true
      loop:
        - http
        - https
    - name: Remove welcome page file
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
